version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/appname/public
permissions:
  - object: /home/ubuntu/appname/public
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
     - file

  AfterInstall:
    - location: script/AfterInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: script/ApplicationStart.sh
      runas: ubuntu
