version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/appname/public
permissions:
   - object: /home/ubuntu/appname/public
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 775
     type:
       - file

