version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/appname/
permissions:
  - object: /home/ubuntu/appname/
    owner: ubuntu
    group: ubuntu
  AfterInstall:
    - location: script/AfterInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: script/ApplicationStart.sh
      runas: ubuntu
