os: linux
files:
   - source: /
     destination: /home/ubuntu/appname/
permissions:
   - object: /home/ubuntu/appname/
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 775
     type:
       - file
hooks:
AfterInstall:
    - location: AfterInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: ApplicationStart.sh
      runas: ubuntu
