bitgo_admin:
  api_address: "http://localhost:3080/api/v1"
  access_token: "f0142e3acc2980139c14b9dbd71b0b495993119b91a6b8001d681f84fcc90a3d"
mediawiki:
  secret: "3eab6c8832c64bf66904f38c9978801c3f0b5deb144ac262ccc9312e4f35c150"
  domain: "localhost"
  username: "WeServeBot"
  password: "q1w2e3r4"
email_provider_username: "e.weserve@gmail.com"
email_provider_password: "aric12345"
facebook_app_id: "1757686594508181"
facebook_secret_key: "78a1acb1051601b3cf9c828b4dc8af2b"
twitter_app_id: "K8A2tZe46ELwIvuIGoqzBiJuf"
twitter_secret_key: "P2dD6a3YsOxIHBXJDr8j6z3cmcyGlvv8dVsSlDoEdExBt3rLqL"
gapp_id: "25015051559-7u7s5egjhngtfolem0ntefsskjhd9tvn.apps.googleusercontent.com"
gapp_secret_key: "0y2KjAZzpHRBTDRsa6d8kGVG"
mailer_sender: "no-reply@youserve.org"
app_secret_key: "ba8af693646f6aeb97ae435836dacb086a02be6bb3fde45064fe0f853bb5d4a6ccf06412ecdfbc27347a1a1223844a53878115c9ec1ea303c025ced4714caf21"
domain_name: "example.com"
default_url: "localhost:3000" #http://dev.weserve.io
