default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: weserve_development

test:
  <<: *default
  database: weserve_test

production:
  <<: *default
  database: weserve_production