production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: weserve_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: weserve_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432